import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  coreSidebar: [
    {
      type: 'category',
      label: 'Vigía Incubation Framework – Core',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'core',
        },
      ],
    },
  ],
};

export default sidebars;
